services:
  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - var.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - var.env
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - var.env
    ports:
      - "4201:80"
    depends_on:
      - backend

  ovenserver:
    build:
      context: ./ovenserver
      dockerfile: Dockerfile
    container_name: ovenserver
    env_file:
      - var.env
    ports:
      - "1935:1935"
      - "9999:9999/udp"
      - "9000:9000"
      - "3333:3333"
      - "3478:3478"
      - "8081:8081"
      - "10000-10009:10000-10009/udp"
      - "20080:20080"
    volumes:
      - data:/mnt/shared_volumes

  nginx:
    image: nginx:latest
    container_name: nginx_cdn
    ports:
      - "9998:9998"
    volumes:
    - data:/var/www/files
    - ./nginx_cdn.conf:/etc/nginx/nginx.conf

volumes:
  mysql_db:
  data:
