services:
  mysql_chat:
    image: mysql:lts
    container_name: mysql_chat
    env_file:
      - var_chat.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_db_chat:/var/lib/mysql

volumes:
  mysql_db_chat:
