services:
  backend-websocket:
    build:
      context: ../backend-websocket-service
      dockerfile: Dockerfile
    container_name: backend-websocket
    depends_on:
      - backend-core
    env_file:
      - ./env/shared/jwt.env
      - ./env/shared/cors.env
      - ./env/shared/rabbitmq.env
    ports:
      - "8082:8080"
    volumes:
      - data_websocket_chat:/app/data

volumes:
  data_websocket_chat:
