services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./env/frontend.env
    ports:
      - "4201:80"
    depends_on:
      - backend-core
