services:
  nginx-image:
    image: nginx:alpine
    container_name: nginx_image_cdn
    ports:
      - "9997:9998"
    volumes:
    - ./data:/var/www/files
    - ./conf/nginx_cdn.conf:/etc/nginx/nginx.conf
